// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDWSbbu7LgPZLXl1cuo-3nH5aPOzaVXo',
    appId: '1:505616466054:web:cb146224031a52368fd107',
    messagingSenderId: '505616466054',
    projectId: 'happy-tails-dccd3',
    authDomain: 'happy-tails-dccd3.firebaseapp.com',
    storageBucket: 'happy-tails-dccd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaGCqKannrpOPMQbTPqZrvSs-jNtCywI',
    appId: '1:505616466054:android:f91b0dc26cffb1f38fd107',
    messagingSenderId: '505616466054',
    projectId: 'happy-tails-dccd3',
    storageBucket: 'happy-tails-dccd3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlDWSbbu7LgPZLXl1cuo-3nH5aPOzaVXo',
    appId: '1:505616466054:web:493bbf3a9211ea0b8fd107',
    messagingSenderId: '505616466054',
    projectId: 'happy-tails-dccd3',
    authDomain: 'happy-tails-dccd3.firebaseapp.com',
    storageBucket: 'happy-tails-dccd3.firebasestorage.app',
  );
}
